# Generated by Django 3.1.2 on 2021-02-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highest_education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maritial_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divorce',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('State_issued_divorce_id', models.CharField(max_length=100)),
                ('Date_of_birth', models.DateTimeField()),
                ('Nationality', models.CharField(max_length=100)),
                ('Highest_education', models.ManyToManyField(to='divorce.Highest_education')),
                ('Maritial_status', models.ManyToManyField(to='divorce.Maritial_status')),
            ],
        ),
    ]
