# Generated by Django 3.1.2 on 2021-02-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divorce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divorce',
            name='Highest_education',
        ),
        migrations.AddField(
            model_name='divorce',
            name='Highest_education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='divorce',
            name='Maritial_status',
        ),
        migrations.AddField(
            model_name='divorce',
            name='Maritial_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divorce',
            name='Nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divorce',
            name='State_issued_divorce_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divorce',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Highest_education',
        ),
        migrations.DeleteModel(
            name='Maritial_status',
        ),
    ]
