# Generated by Django 3.1.2 on 2021-02-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divorce', '0002_auto_20210217_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorce',
            name='Date_of_birth',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
